/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.test.pipeline;

public class App {
    public String getGreeting() {
        return null;
        //return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
